#!/bin/bash

mkdir -p /sftpd/etc/ssh
mkdir -p /sftpd/var/run
cp /root/sshd_config /sftpd/etc/ssh/sshd_config
ssh-keygen -t rsa -f /sftpd/etc/ssh/ssh_host_rsa_key

# Run SSH
/usr/sbin/sshd -f /sftpd/etc/ssh/sshd_config -D
